(TeX-add-style-hook "JMC_dis"
 (lambda ()
    (LaTeX-add-bibliographies
     "mybiblio")
    (LaTeX-add-labels
     "e:xifull"
     "e:jetexpansion"
     "e:jetexpansion-tw3"
     "e:jetspectral"
     "eq:jetfnsprops"
     "eq:jet_vs_spectral"
     "eq:F2"
     "eq:mjet"
     "eq:xi2_chiral_cond"
     "e:xi_A"
     "eq:SIDIS_to_DIS"
     "eq:Wsidis_ini"
     "e:crossdis"
     "e:FUTint"
     "e:FLTint"
     "e:g2"
     "f:g2contrib"
     "eq:BC")
    (TeX-add-symbols
     '("todo" 1)
     "Pslash"
     "kslash"
     "lslash"
     "nslash"
     "vslash"
     "Sslash"
     "Dslash"
     "epsslash"
     "Tr"
     "xbj"
     "de"
     "ii"
     "mj"
     "mjs")
    (TeX-run-style-hooks
     "datetime"
     "slashed"
     "dcolumn"
     "multirow"
     "hhline"
     "graphicx"
     "bm"
     "amssymb"
     "amsmath"
     "tbtags"
     "latex2e"
     "revtex410"
     "revtex4"
     "preprintnumbers"
     "floatfix"
     "nofootinbib")))

